GET http://localhost:3001/authorization/
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjUwMzc4NDQsImV4cCI6MTYyNTY0MjY0NCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAxL2F1dGhvcml6YXRpb24iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvbG9naW4iLCJqdGkiOiI2MGRjMWMxM2U5MjllYzBkYTQ0MWE3MTYifQ.TGVUxLjoiOVC37R_gWmJ1TazLM50hzi5VNrE1LwIZ4s