PUT http://localHost:3001/api/blogs/60f66f9fedc0b40c6c983f64
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkRtYkJ5TGhreGtNMzBQUWExRXBvbiJ9.eyJpYXQiOjE2MjQ3NzYzMTAsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS8iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvbG9naW4iLCJzdWIiOiI2MDkzYTU2MDczZWU4NzE1MzRjODBkNDgifQ.XY8yLRKPdO_sJvxMYr-YTQpkAom_Y6_9UUyibvcPYhQR8aUb2c6lE3zqSONohc8uvpcRQg3HG-9yeSS0oIfKn8qIAqfpUTBxTylEo3oGS9iNcFDXD2IJLEaTz4PEXV1iGyAibgIHbYNRmydhH4C5Pv7OEiGyccIkS8FieotDlxgDtgxHa03-1ACxnAtvb1nnnelQMT9VqwHo7XB5bf6VEXgwfhGcI2z7IOq0ySzQRjIIiMMsZoC9xER5ZIYfxIVj2c_r9OvM8E2469pMmHyzsOYkQrcfoTOKJ44e4ET0wkSq0bvm5cBUCn6vmVECSnb-yTJylGV-NI-ggrFAFYHxuQ

{
	"likes": "1"
}