GET http://localhost:3001/authorization
Content-Type: application/json
Cookie: refreshToken = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzY3OTAwNDQsImV4cCI6MTYzNzM5NDg0NCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAxL2F1dGhvcml6YXRpb24iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDEvbG9naW4iLCJqdGkiOiI2MThmNmYxY2YwNjAwMDA0ODQ1ZjI3YWMifQ.IRhEGLheTsQ8qlr4E3NYO6glOkNBSuWkRpZGEgCRoLA